# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
 exclude:
    - r:  devel
      os: osx
    - r:  oldrel
      os: osx

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
